-- MySQL Script generated by MySQL Workbench
-- Qua 27 Mai 2015 17:13:27 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rede
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rede
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rede` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rede` ;

-- -----------------------------------------------------
-- Table `rede`.`reference_units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede`.`reference_units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(525) NULL,
  `contact_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reference_units_farmers1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_reference_units_farmers1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `rede`.`farmers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede`.`farmers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede`.`farmers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `reference_unit_id` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  `address_number` INT NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `postal_code` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_farmers_reference_units1_idx` (`reference_unit_id` ASC),
  CONSTRAINT `fk_farmers_reference_units1`
    FOREIGN KEY (`reference_unit_id`)
    REFERENCES `rede`.`reference_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede`.`produces_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede`.`produces_categories` (
  `farmer_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  INDEX `fk_produces_farmers1_idx` (`farmer_id` ASC),
  INDEX `fk_produces_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_produces_farmers1`
    FOREIGN KEY (`farmer_id`)
    REFERENCES `rede`.`farmers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produces_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `rede`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
